services:
  it-tools:
    container_name: it-tools
    image: sharevb/it-tools:latest@sha256:d08fa3dece36b1eb54de1a6b8433a8380b75a00a7ed47d5082e9974df53bb06d
    pull_policy: always
    restart: unless-stopped
    ports:
      - 8080:8080       # Since Docker base image is now nginx-unpriviledged, docker image now listen to 8080 and no more 80. 