<script setup lang="ts">
import { useI18n } from 'vue-i18n';
const { t } = useI18n();
import UnitsConverter from '@/components/UnitsConverter.vue';

const supportedUnits = {
  'm³': { value: 'cubic meter/stere', label: t('tools.volume-converter.texts.label-cubic-meter-stere') },
  'Pm³': { value: 'cubic petameter', label: t('tools.volume-converter.texts.label-cubic-petameter') },
  'Tm³': { value: 'cubic terameter', label: t('tools.volume-converter.texts.label-cubic-terameter') },
  'Gm³': { value: 'cubic gigameter', label: t('tools.volume-converter.texts.label-cubic-gigameter') },
  'Mm³': { value: 'cubic megameter', label: t('tools.volume-converter.texts.label-cubic-megameter') },
  'km³': { value: 'cubic kilometer', label: t('tools.volume-converter.texts.label-cubic-kilometer') },
  'hm³': { value: 'cubic hectometer', label: t('tools.volume-converter.texts.label-cubic-hectometer') },
  'dam³': { value: 'cubic decameter', label: t('tools.volume-converter.texts.label-cubic-decameter') },
  'dm³': { value: 'cubic decimeter', label: t('tools.volume-converter.texts.label-cubic-decimeter') },
  'cm³': { value: 'cubic centimeter', label: t('tools.volume-converter.texts.label-cubic-centimeter') },
  'mm³': { value: 'cubic millimeter', label: t('tools.volume-converter.texts.label-cubic-millimeter') },
  'µm³': { value: 'cubic micrometer', label: t('tools.volume-converter.texts.label-cubic-micrometer') },
  'nm³': { value: 'cubic nanometer', label: t('tools.volume-converter.texts.label-cubic-nanometer') },
  'pm³': { value: 'cubic picometer', label: t('tools.volume-converter.texts.label-cubic-picometer') },
  'fm³': { value: 'cubic femtometer', label: t('tools.volume-converter.texts.label-cubic-femtometer') },
  L: { value: 'liter', label: t('tools.volume-converter.texts.label-liter') },
  Pl: { value: 'petaliter', label: t('tools.volume-converter.texts.label-petaliter') },
  Tl: { value: 'teraliter', label: t('tools.volume-converter.texts.label-teraliter') },
  Gl: { value: 'gigaliter', label: t('tools.volume-converter.texts.label-gigaliter') },
  Ml: { value: 'megaliter', label: t('tools.volume-converter.texts.label-megaliter') },
  kL: { value: 'kiloliter', label: t('tools.volume-converter.texts.label-kiloliter') },
  hL: { value: 'hectoliter', label: t('tools.volume-converter.texts.label-hectoliter') },
  daL: { value: 'decaliter', label: t('tools.volume-converter.texts.label-decaliter') },
  dL: { value: 'deciliter', label: t('tools.volume-converter.texts.label-deciliter') },
  cL: { value: 'centiliter', label: t('tools.volume-converter.texts.label-centiliter') },
  mL: { value: 'milliliter', label: t('tools.volume-converter.texts.label-milliliter') },
  µL: { value: 'microliter', label: t('tools.volume-converter.texts.label-microliter') },
  nL: { value: 'nanoliter', label: t('tools.volume-converter.texts.label-nanoliter') },
  pL: { value: 'picoliter', label: t('tools.volume-converter.texts.label-picoliter') },
  fL: { value: 'femtoliter', label: t('tools.volume-converter.texts.label-femtoliter') },
  'mi³': { value: 'cubic mile', label: t('tools.volume-converter.texts.label-cubic-mile') },
  'ac ft': { value: 'acre-foot', label: t('tools.volume-converter.texts.label-acre-foot') },
  'yd³': { value: 'cubic yard', label: t('tools.volume-converter.texts.label-cubic-yard') },
  'ft³': { value: 'cubic foot', label: t('tools.volume-converter.texts.label-cubic-foot') },
  'board feet': { value: 'board feet', label: t('tools.volume-converter.texts.label-board-feet') },
  'in³': { value: 'cubic inch', label: t('tools.volume-converter.texts.label-cubic-inch') },
  MTON: { value: 'measurement ton', label: t('tools.volume-converter.texts.label-measurement-ton') },
  'imp bbl': { value: 'imperial barrel', label: t('tools.volume-converter.texts.label-imperial-barrel') },
  'imp bsh': { value: 'imperial bushel', label: t('tools.volume-converter.texts.label-imperial-bushel') },
  pk: { value: 'imperial peck', label: t('tools.volume-converter.texts.label-imperial-peck') },
  'imp gal': { value: 'imperial gallon', label: t('tools.volume-converter.texts.label-imperial-gallon') },
  'imp qt': { value: 'imperial quart', label: t('tools.volume-converter.texts.label-imperial-quart') },
  'imp pt': { value: 'imperial pint', label: t('tools.volume-converter.texts.label-imperial-pint') },
  'imp fl oz': { value: 'imperial fluid ounce', label: t('tools.volume-converter.texts.label-imperial-fluid-ounce') },
  tsp: { value: 'teaspoon', label: t('tools.volume-converter.texts.label-teaspoon') },
  tbsp: { value: 'tablespoon', label: t('tools.volume-converter.texts.label-tablespoon') },
  'fl oz': { value: 'US fluid ounce', label: t('tools.volume-converter.texts.label-us-fluid-ounce') },
  c: { value: 'cup', label: t('tools.volume-converter.texts.label-cup') },
  'US lc': { value: 'US legal cup', label: t('tools.volume-converter.texts.label-us-legal-cup') },
  pt: { value: 'US liquid pint', label: t('tools.volume-converter.texts.label-us-liquid-pint') },
  qt: { value: 'US liquid quart', label: t('tools.volume-converter.texts.label-us-liquid-quart') },
  gal: { value: 'US liquid gallon', label: t('tools.volume-converter.texts.label-us-liquid-gallon') },
  'US bsh': { value: 'US bushel', label: t('tools.volume-converter.texts.label-us-bushel') },
  'US pk': { value: 'US peck', label: t('tools.volume-converter.texts.label-us-peck') },
  'US dry gal': { value: 'US dry gallon', label: t('tools.volume-converter.texts.label-us-dry-gallon') },
  'US dry bbl': { value: 'US dry barrel', label: t('tools.volume-converter.texts.label-us-dry-barrel') },
  'US dry qt': { value: 'US dry quart', label: t('tools.volume-converter.texts.label-us-dry-quart') },
  'US dry pt': { value: 'US dry pint', label: t('tools.volume-converter.texts.label-us-dry-pint') },
};
</script>

<template>
  <UnitsConverter default-unit="m³" :supported-units="supportedUnits" label-width="150px" />
</template>
